/** Read/write the `<asset>.meta.json` sidecar that lives next to binary asset
 *  sources (GLB, PNG, HDR, ...). Used by the texture + model reimport handlers
 *  (and anywhere else that touches a sidecar — drop new callers in here so
 *  format/atomicity concerns live in one place).
 *
 *  Atomicity: the sidecar is the source of truth for the asset's GUID and its
 *  content-cache bookkeeping. A crash mid-write would otherwise leave a
 *  truncated JSON, which `readMetaSidecar` quietly catches as `{}` — the next
 *  reimport then re-mints the GUID (breaking every external ref) and re-runs
 *  every expensive conversion. We avoid that by writing to a sibling
 *  `<sidecar>.tmp` and renaming into place; `fs.renameSync` is atomic on POSIX
 *  and Windows, so either the new contents land in full or the old file stays.
 *
 *  Committed vs machine-local split: the derived-file byte SIZES (an atlas PNG's
 *  bytes, a LOD GLB's bytes, ...) are NOT byte-reproducible across build hosts —
 *  a native encoder like msdf-atlas-gen or ffmpeg emits a slightly different-sized
 *  file on Windows vs macOS from the same input. Committing those sizes churns the
 *  sidecar between clones for zero functional gain: nothing at runtime reads them,
 *  they're inspector-only display. So `writeMetaSidecar` peels the volatile size
 *  stats out into a gitignored `<asset>.meta.local.json` and `readMetaSidecar`
 *  merges them back (local wins) — the committed `.meta.json` stays stable across
 *  hosts while the inspector still shows the live sizes. The STRUCTURAL cache
 *  fields (variants, lodPaths, lodDistances, dims, glyphCount, ...) — which the
 *  serving/build/runtime DO consume and which are stable across a shared
 *  provisioned toolchain — remain in the committed sidecar.
 *
 *  `modelCache.hash` is the ONE structural field that fails that "stable across
 *  hosts" test, so it is peeled too (#127). It is the validity key for a cache
 *  that is itself gitignored, and it is machine-dependent BY CONSTRUCTION: both
 *  `hashKey` (model-cache.ts) and `riggedHash` (rigged-model-optimize.ts) mix in
 *  local CLI versions, and `riggedHash` additionally encodes whether `toktx`
 *  exists at all — and KTX-Software is a manual install, so some clones have it
 *  and some do not. Identical source bytes + identical settings therefore hash
 *  DIFFERENTLY per machine, and with four clones it can never converge: each
 *  rewrites the sidecar when it builds and the next rewrites it back. Measured:
 *  commit 471ca0cf's entire GLB-sidecar diff was 7 hash lines and nothing else.
 *  Nothing breaks without it — the serving path already treats a missing/stale
 *  hash as a cache miss and re-bakes (see `autoBakeThenServe` in
 *  backend/staticAssets.ts, written for the sibling "fresh checkout" case).
 *  The OTHER blocks' hashes stay committed: they mix only source bytes, settings
 *  and an in-repo encoder version, so they ARE reproducible across machines.
 */

import fs from 'fs';
import {
  classifyJsonFormatVersion,
  type FormatVerdict,
} from '../packages/modoki/src/runtime/core/formatVersion';
// The one GUID validator — not a third copy of the regex (CLAUDE.md § single source of truth).
import { isGuid } from '../packages/modoki/src/runtime/core/assetRefRules';

/** The FORMAT version of the `.meta.json` sidecar document — how the file is laid
 *  out (which top-level fields exist, how cache blocks are shaped), NOT a version
 *  of the asset it describes. `writeMetaSidecar` compares this against whatever
 *  version is already on disk on every write and refuses to overwrite a sidecar
 *  written by a newer build (see `assertSidecarWritable`). Bumping this number
 *  means deciding what older-versioned sidecars this build can still read — do
 *  not bump it casually. */
export const SIDECAR_FORMAT_VERSION = 2;

function sidecarPath(absPath: string): string {
  return absPath + '.meta.json';
}

/** Where an unparsable sidecar is moved before it is replaced (#778).
 *
 *  Gitignored: machine-local recovery evidence, not something to commit.
 *
 *  On the asset scanner: a `.corrupt` path is already classified as a non-asset by
 *  `detectType`'s unknown-extension fallthrough (`EXT_TYPE['.corrupt']` is undefined), so it is
 *  not scanned. `vite-asset-scanner.ts` also names the suffix explicitly — belt-and-braces
 *  against a future `EXT_TYPE` entry, NOT the thing currently doing the work. An earlier version
 *  of this comment claimed the explicit clause was load-bearing and that the file would otherwise
 *  be minted a GUID of its own; that was inferred, never observed, and is false — measured by
 *  passing a bare `.corrupt` path (which the clause does not match) and getting `null` anyway. */
export const CORRUPT_SIDECAR_SUFFIX = '.corrupt';

/** The gitignored sibling holding this machine's regenerated byte-size stats. */
function localSidecarPath(absPath: string): string {
  return absPath + '.meta.local.json';
}

/** Content-cache blocks that carry byte-size stats. */
const CACHE_BLOCKS = ['textureCache', 'modelCache', 'fontCache', 'audioCache', 'environmentCache', 'atlasCache'] as const;
type CacheBlock = (typeof CACHE_BLOCKS)[number];
/** Machine-local, inspector-only size fields peeled out of EVERY cache block. */
const VOLATILE_STAT_KEYS = ['variantBytes', 'lodBytes', 'triCounts', 'bytes'] as const;
/** Extra per-block keys that are host-dependent rather than merely volatile, so
 *  committing them churns the tree between clones. See the module note for why
 *  `modelCache.hash` is the only one. */
const HOST_LOCAL_KEYS: Partial<Record<CacheBlock, readonly string[]>> = { modelCache: ['hash'] };

/** Every key peeled out of `block` into the gitignored local sidecar. */
function localKeysFor(block: CacheBlock): readonly string[] {
  const extra = HOST_LOCAL_KEYS[block];
  return extra ? [...VOLATILE_STAT_KEYS, ...extra] : VOLATILE_STAT_KEYS;
}

/** Read the sidecar JSON — the committed `.meta.json` with this machine's local
 *  byte-size stats merged back in (local values WIN, since they reflect what this
 *  host actually produced). `{}` when the committed sidecar is missing/unparsable.
 *
 *  ⚠️ **That `{}` deliberately conflates "missing" with "unparsable", and callers must not
 *  read it as "there was nothing here."** #778 was this conflation's consequence: a caller
 *  read `{}` from a conflict-marked sidecar, merged into it, and wrote the result back over
 *  the authored fields. The DATA-LOSS half is now closed at the write path — `writeMetaSidecar`
 *  quarantines an unreadable sidecar before overwriting it — so this merge-read stays simple
 *  and total on purpose. A caller that needs the distinction itself calls
 *  {@link classifySidecarOnDisk}, which is exported for exactly that. */
export function readMetaSidecar(absPath: string): Record<string, unknown> {
  const sidecar = sidecarPath(absPath);
  if (!fs.existsSync(sidecar)) return {};
  let meta: Record<string, unknown>;
  try { meta = JSON.parse(fs.readFileSync(sidecar, 'utf-8')); } catch { return {}; }
  const localPath = localSidecarPath(absPath);
  if (fs.existsSync(localPath)) {
    try {
      const local = JSON.parse(fs.readFileSync(localPath, 'utf-8')) as Record<string, Record<string, unknown>>;
      for (const block of CACHE_BLOCKS) {
        const localBlock = local[block];
        if (!localBlock || typeof localBlock !== 'object') continue;
        const target = (meta[block] ??= {}) as Record<string, unknown>;
        for (const k of localKeysFor(block)) if (k in localBlock) target[k] = localBlock[k];
      }
    } catch { /* unreadable local stats → whatever the committed sidecar has stands */ }
  }
  return meta;
}

/** Classify the COMMITTED sidecar on disk against this build's format version — a plain,
 *  non-merging read (unlike `readMetaSidecar`, which merges in local stats).
 *
 *  ⚠️ **This replaced a `versionOnDisk()` that returned `undefined` for FOUR different
 *  conditions** — file missing, unparsable JSON, not an object, non-numeric `version` — which
 *  made `absent` and `unreadable` the same answer and was the whole of #778: the guard below
 *  gated on `!== undefined && > CONST`, so a sidecar full of merge-conflict markers read as
 *  "no version" and **failed open on exactly the input it existed to catch**. The distinction
 *  now comes from the shared classifier, so every caller can have it — see
 *  `docs/format-versioning.md` § 2a and `runtime/core/formatVersion.ts`.
 *
 *  A missing FILE is `absent` (there is nothing to protect); an unreadable one is
 *  `unreadable` (there may be authored fields in there, damaged but present). */
export function classifySidecarOnDisk(absPath: string): FormatVerdict {
  const sidecar = sidecarPath(absPath);
  let text: string;
  try { text = fs.readFileSync(sidecar, 'utf-8'); } catch { return { kind: 'absent' }; }
  return classifyJsonFormatVersion(text, SIDECAR_FORMAT_VERSION);
}

/** Throws if the sidecar at `absPath` was written by a NEWER format than this
 *  build knows — call before doing expensive reimport work so a too-new sidecar
 *  aborts fast, before `writeMetaSidecar` would refuse it anyway.
 *
 *  Deliberately throws on `too-new` ONLY. An `unreadable` sidecar is not a format refusal —
 *  it is damaged data, and its disposition is to be quarantined and replaced
 *  ({@link quarantineCorruptSidecar}), not to abort the reimport. Collapsing the two back
 *  together is the #778 defect. */
/** The `version` value as it literally sits on disk, without classification — used only by
 *  `assertSidecarWritable` to keep a numerically-newer NON-INTEGER version refusing. Returns
 *  `undefined` when the file is missing, unparsable, or has no `version`. */
function rawSidecarVersion(absPath: string): unknown {
  try {
    const parsed: unknown = JSON.parse(fs.readFileSync(sidecarPath(absPath), 'utf-8'));
    if (!parsed || typeof parsed !== 'object') return undefined;
    return (parsed as Record<string, unknown>).version;
  } catch {
    return undefined;
  }
}

export function assertSidecarWritable(absPath: string): void {
  const verdict = classifySidecarOnDisk(absPath);
  // ⚠️ A NON-INTEGER version that is numerically newer still refuses. Classification calls
  // `3.5` `unreadable`, which is right for a save (malformed data normalizes) but would be a
  // RELAXATION here: the old `versionOnDisk` returned `3.5`, and `3.5 > 2` threw. Without this
  // the file would be quarantined and replaced instead of left alone — a document that is
  // plainly from the future, treated as damage. No build writes one, so this guards a shape
  // that is currently hypothetical; it costs one line and keeps the refusal monotonic.
  const rawVersion = rawSidecarVersion(absPath);
  if (typeof rawVersion === 'number' && Number.isFinite(rawVersion) && rawVersion > SIDECAR_FORMAT_VERSION) {
    throw new Error(
      `Sidecar ${sidecarPath(absPath)} is format version ${rawVersion}, newer than this build's ` +
      `SIDECAR_FORMAT_VERSION (${SIDECAR_FORMAT_VERSION}) — refusing to overwrite a sidecar ` +
      `written by a newer build — merge the branch that bumped the format.`
    );
  }
  if (verdict.kind === 'too-new') {
    throw new Error(
      `Sidecar ${sidecarPath(absPath)} is format version ${verdict.version}, newer than this build's ` +
      `SIDECAR_FORMAT_VERSION (${SIDECAR_FORMAT_VERSION}) — refusing to overwrite a sidecar ` +
      `written by a newer build — merge the branch that bumped the format.`
    );
  }
}

/**
 * Move an unparsable sidecar aside instead of destroying it, and report where it went.
 *
 * The #778 case: `<<<<<<<`/`=======`/`>>>>>>>` conflict markers in a committed `.meta.json`.
 * Several hundred sidecars are tracked and shared through the remote by six clones on five long-lived
 * branches, so two clones editing one asset's import settings is an ordinary conflict — and
 * the previous behaviour replaced the whole document with `{id}`, discarding the texture
 * import settings and every hand-drawn sprite slice (each carrying its OWN GUID that scenes
 * reference), while returning `true`.
 *
 * ⚠️ **tmp+rename does not cover this case and never did.** That mechanism closes the
 * *crash mid-write* hole described in this module's header; a conflict-marked file is a
 * complete, deliberate write of bytes that happen not to parse.
 *
 * Owner's call, 2026-09-06: rename rather than refuse. Refusing outright is safe but leaves an
 * asset that can never be re-stamped without a human deleting the file, and the scan path may
 * re-hit it every run. Renaming keeps the scanner moving AND keeps the authored bytes
 * recoverable by hand.
 *
 * No-op (returns `undefined`) unless the sidecar is genuinely `unreadable`, so a caller can
 * invoke it unconditionally before a write. An existing `.corrupt` file is overwritten: the
 * replacement written immediately afterwards always parses, so a second quarantine of the same
 * asset can only follow fresh corruption, and that is the copy worth keeping.
 *
 * ⚠️ **Throws if the file cannot be moved aside**, rather than reporting "nothing to do". A
 * caller invokes this to earn the right to overwrite; returning quietly on failure would hand
 * back that right while the authored bytes were still there — the same fail-open shape as the
 * `undefined`-for-four-conditions reader this change removes.
 */
/**
 * Recover the asset's GUID from a sidecar that does not parse.
 *
 * ⚠️ **Preserving the bytes is not the same as preserving the ASSET.** Quarantining alone still
 * loses the `id`, and losing the `id` is the expensive half: the next scan finds no GUID, mints a
 * fresh one, and every scene/prefab/mesh reference to the old one dangles. The authored fields in
 * the `.corrupt` file can be merged back by hand at leisure; a re-minted GUID silently breaks
 * content that was working.
 *
 * A merge conflict wraps only the conflicting hunk, so the `"id"` line is almost always intact
 * and outside the markers. This reads it textually, because by definition `JSON.parse` cannot.
 *
 * ⚠️ **Refuses to guess when the id itself conflicts.** If the damaged text carries two or more
 * DIFFERENT guid-shaped `id` values, both sides of a conflict touched it and there is no way to
 * tell which one the scenes reference — salvaging the first would be a coin flip that looks like
 * a recovery. Returns `undefined` there, so the honest re-mint happens and both candidates remain
 * in the `.corrupt` file for a human.
 */
export function salvageSidecarId(text: string): string | undefined {
  const found = new Set<string>();
  for (const m of text.matchAll(/"id"\s*:\s*"([^"\\]+)"/g)) {
    if (isGuid(m[1])) found.add(m[1]);
  }
  return found.size === 1 ? [...found][0] : undefined;
}

/** The salvageable `id` of a sidecar that does not parse, or `undefined` when it parses fine
 *  (nothing to salvage) or carries no unambiguous guid. Reads the file itself, so it must be
 *  called BEFORE `quarantineCorruptSidecar` moves it. */
export function salvageIdIfCorrupt(absPath: string): string | undefined {
  if (classifySidecarOnDisk(absPath).kind !== 'unreadable') return undefined;
  try {
    return salvageSidecarId(fs.readFileSync(sidecarPath(absPath), 'utf-8'));
  } catch {
    return undefined;
  }
}

export function quarantineCorruptSidecar(absPath: string): string | undefined {
  if (classifySidecarOnDisk(absPath).kind !== 'unreadable') return undefined;
  const sidecar = sidecarPath(absPath);
  const quarantined = sidecar + CORRUPT_SIDECAR_SUFFIX;
  try {
    fs.renameSync(sidecar, quarantined);
  } catch (e) {
    throw new Error(
      `Sidecar ${sidecar} does not parse and could not be moved to ${quarantined} ` +
      `— refusing to overwrite it, because its authored fields are not recoverable from the ` +
      `source asset.`,
      { cause: e },
    );
  }
  console.warn(
    `[assets] ${sidecar} did not parse (merge conflict markers?) — moved to ${quarantined} and ` +
    `recreating. Its authored fields (texture import settings, sprite slices and their GUIDs) ` +
    `are in that file; resolve it by hand and merge them back.`
  );
  return quarantined;
}

/** Atomically write the sidecar. The committed `.meta.json` gets everything EXCEPT
 *  the volatile byte-size stats, which go to a gitignored `.meta.local.json`. Both
 *  writes use tmp+rename for crash-atomicity. Refuses (throws, writes nothing) if
 *  the sidecar already on disk carries a newer format version than this build's
 *  `SIDECAR_FORMAT_VERSION` — see `assertSidecarWritable`. Stamps
 *  `SIDECAR_FORMAT_VERSION` onto the written sidecar itself; callers do not
 *  supply `version`. */
export function writeMetaSidecar(absPath: string, meta: Record<string, unknown>): void {
  assertSidecarWritable(absPath);
  // ⚠️ Capture the salvageable `id` BEFORE the quarantine moves the file away. The editor panels
  // reach here via `/api/read-meta`, which returns `{}` for an unparsable sidecar exactly as it
  // does for a missing one — so the payload they POST carries no `id`, and without this the write
  // below would produce an id-less sidecar and the next scan would mint a fresh GUID, dangling
  // every scene/prefab reference. Preserving the bytes does not preserve the ASSET; this does.
  const salvagedId = salvageIdIfCorrupt(absPath);
  // An unparsable sidecar is moved aside, not overwritten (#778). This sits at the choke point
  // deliberately: every reimport handler reaches disk through here, and each one has already
  // lost the authored fields by this line — `readMetaSidecar` returns `{}` for a corrupt file
  // just as it does for a missing one — so without this the merge they *think* they are doing
  // is a wholesale replacement. Quarantining here fixes all of them at once rather than
  // per-handler.
  quarantineCorruptSidecar(absPath);
  const committed = JSON.parse(JSON.stringify(meta)) as Record<string, unknown>;
  // Only when the caller supplied none — a caller that knows the id (the reimport handlers, which
  // read it before editing) always wins over a textual salvage.
  if (salvagedId && !isGuid(committed.id as string | undefined)) committed.id = salvagedId;
  committed.version = SIDECAR_FORMAT_VERSION;
  const local: Record<string, Record<string, unknown>> = {};
  for (const block of CACHE_BLOCKS) {
    const b = committed[block] as Record<string, unknown> | undefined;
    if (!b || typeof b !== 'object') continue;
    for (const k of localKeysFor(block)) {
      if (k in b) {
        (local[block] ??= {})[k] = b[k];
        delete b[k];
      }
    }
  }
  writeJsonAtomic(sidecarPath(absPath), committed);
  const localPath = localSidecarPath(absPath);
  if (Object.keys(local).length > 0) writeJsonAtomic(localPath, local);
  else if (fs.existsSync(localPath)) fs.rmSync(localPath, { force: true }); // no stats now → drop a stale local file
}

function writeJsonAtomic(final: string, obj: unknown): void {
  const tmp = final + '.tmp';
  // Trailing newline: these sidecars are COMMITTED, and without it every rewrite shows
  // up as "\ No newline at end of file" in the diff. The tree was split 65/198 on this,
  // so sidecars churned purely on formatting depending on which tool wrote them last.
  fs.writeFileSync(tmp, JSON.stringify(obj, null, 2) + '\n');
  fs.renameSync(tmp, final);
}
