/** Read/write the `<asset>.meta.json` sidecar that lives next to binary asset
 *  sources (GLB, PNG, HDR, ...). Used by the texture + model reimport handlers
 *  (and anywhere else that touches a sidecar — drop new callers in here so
 *  format/atomicity concerns live in one place).
 *
 *  Atomicity: the sidecar is the source of truth for the asset's GUID and its
 *  content-cache bookkeeping. A crash mid-write would otherwise leave a
 *  truncated JSON, which `readMetaSidecar` quietly catches as `{}` — the next
 *  reimport then re-mints the GUID (breaking every external ref) and re-runs
 *  every expensive conversion. We avoid that by writing to a sibling
 *  `<sidecar>.tmp` and renaming into place; `fs.renameSync` is atomic on POSIX
 *  and Windows, so either the new contents land in full or the old file stays.
 *
 *  Committed vs machine-local split: the derived-file byte SIZES (an atlas PNG's
 *  bytes, a LOD GLB's bytes, ...) are NOT byte-reproducible across build hosts —
 *  a native encoder like msdf-atlas-gen or ffmpeg emits a slightly different-sized
 *  file on Windows vs macOS from the same input. Committing those sizes churns the
 *  sidecar between clones for zero functional gain: nothing at runtime reads them,
 *  they're inspector-only display. So `writeMetaSidecar` peels the volatile size
 *  stats out into a gitignored `<asset>.meta.local.json` and `readMetaSidecar`
 *  merges them back (local wins) — the committed `.meta.json` stays stable across
 *  hosts while the inspector still shows the live sizes. The STRUCTURAL cache
 *  fields (hash, variants, lodPaths, lodDistances, dims, glyphCount, ...) — which
 *  the serving/build/runtime DO consume and which are stable across a shared
 *  provisioned toolchain — remain in the committed sidecar.
 */

import fs from 'fs';

function sidecarPath(absPath: string): string {
  return absPath + '.meta.json';
}
/** The gitignored sibling holding this machine's regenerated byte-size stats. */
function localSidecarPath(absPath: string): string {
  return absPath + '.meta.local.json';
}

/** Content-cache blocks that carry byte-size stats. */
const CACHE_BLOCKS = ['textureCache', 'modelCache', 'fontCache', 'audioCache', 'environmentCache', 'atlasCache'] as const;
/** Machine-local, inspector-only size fields peeled out of the committed sidecar.
 *  Everything else in a cache block (hash + structural fields) stays committed. */
const VOLATILE_STAT_KEYS = ['variantBytes', 'lodBytes', 'triCounts', 'bytes'] as const;

/** Read the sidecar JSON — the committed `.meta.json` with this machine's local
 *  byte-size stats merged back in (local values WIN, since they reflect what this
 *  host actually produced). `{}` when the committed sidecar is missing/unparsable. */
export function readMetaSidecar(absPath: string): Record<string, unknown> {
  const sidecar = sidecarPath(absPath);
  if (!fs.existsSync(sidecar)) return {};
  let meta: Record<string, unknown>;
  try { meta = JSON.parse(fs.readFileSync(sidecar, 'utf-8')); } catch { return {}; }
  const localPath = localSidecarPath(absPath);
  if (fs.existsSync(localPath)) {
    try {
      const local = JSON.parse(fs.readFileSync(localPath, 'utf-8')) as Record<string, Record<string, unknown>>;
      for (const block of CACHE_BLOCKS) {
        const localBlock = local[block];
        if (!localBlock || typeof localBlock !== 'object') continue;
        const target = (meta[block] ??= {}) as Record<string, unknown>;
        for (const k of VOLATILE_STAT_KEYS) if (k in localBlock) target[k] = localBlock[k];
      }
    } catch { /* unreadable local stats → whatever the committed sidecar has stands */ }
  }
  return meta;
}

/** Atomically write the sidecar. The committed `.meta.json` gets everything EXCEPT
 *  the volatile byte-size stats, which go to a gitignored `.meta.local.json`. Both
 *  writes use tmp+rename for crash-atomicity. */
export function writeMetaSidecar(absPath: string, meta: Record<string, unknown>): void {
  const committed = JSON.parse(JSON.stringify(meta)) as Record<string, unknown>;
  const local: Record<string, Record<string, unknown>> = {};
  for (const block of CACHE_BLOCKS) {
    const b = committed[block] as Record<string, unknown> | undefined;
    if (!b || typeof b !== 'object') continue;
    for (const k of VOLATILE_STAT_KEYS) {
      if (k in b) {
        (local[block] ??= {})[k] = b[k];
        delete b[k];
      }
    }
  }
  writeJsonAtomic(sidecarPath(absPath), committed);
  const localPath = localSidecarPath(absPath);
  if (Object.keys(local).length > 0) writeJsonAtomic(localPath, local);
  else if (fs.existsSync(localPath)) fs.rmSync(localPath, { force: true }); // no stats now → drop a stale local file
}

function writeJsonAtomic(final: string, obj: unknown): void {
  const tmp = final + '.tmp';
  fs.writeFileSync(tmp, JSON.stringify(obj, null, 2));
  fs.renameSync(tmp, final);
}
