/** Strip the Facebook iOS SDK out of `@capacitor-firebase/authentication`'s SPM manifest (#1062).
 *
 *  WHY. The plugin's `Package.swift` declares `facebook-ios-sdk` as a package dependency, lists
 *  `FacebookCore` + `FacebookLogin` as products of its one target, and defines
 *  `RGCFA_INCLUDE_FACEBOOK`. SPM has no optional products, so EVERY app depending on the plugin
 *  links and embeds the Facebook SDK — four frameworks plus resource bundles — whatever the
 *  plugin's `providers` config says (that config, like the podspec's optional Facebook subspec,
 *  never reaches an SPM build). Court signs in with Apple + Google only, and the Facebook SDK's own
 *  privacy manifests declare `NSPrivacyTracking: true`, which Apple folds into the app's privacy
 *  report. Observed in a Court simulator build: `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework`,
 *  `FBAEMKit.framework`, `FBSDKCoreKit_Basics.framework` and three `Facebook_*.bundle`s in `App.app`.
 *
 *  THE PATCH. Remove the four lines that name Facebook: the `.package(url: …facebook-ios-sdk…)`
 *  dependency, the two `.product(…, package: "facebook-ios-sdk")` entries and the
 *  `.define("RGCFA_INCLUDE_FACEBOOK")`. The define matters as much as the products: every FBSDK
 *  import and call in the plugin's Swift sits behind `#if RGCFA_INCLUDE_FACEBOOK`
 *  (`ios/Plugin/Handlers/FacebookAuthProviderHandler.swift`), so dropping the products alone would
 *  leave that code compiling against a module that is no longer there. (Android needs nothing: its
 *  `build.gradle` already makes Facebook opt-in via `rgcfaIncludeFacebook`, default false.)
 *
 *  WHERE IT RUNS. `healNativeProject`, after that sequence's own `npm install` — the one seam that
 *  runs before every native build on both the editor Build menu and `build-web.mjs --target native`,
 *  under the build claim. An `npm install` that re-extracts the plugin restores the original
 *  manifest; the next build's heal strips it again. It is engine-side on purpose: any game that
 *  depends on the plugin gets it (wordweave the day #927 lands), none has to opt in.
 *
 *  THE GUARD. If any line would still mention Facebook after the strip, that is a REFUSAL, not a
 *  warning — and NOTHING is written. That is how a plugin upgrade that reshapes the manifest (a
 *  wrapped `.package(` call, a renamed product) fails the build instead of silently shipping the SDK
 *  again. Deciding BEFORE writing is load-bearing: a partial strip (the one-line elements gone, a
 *  wrapped `.product` left naming a package no longer declared) breaks SPM resolution for every
 *  later build, including a plain Xcode one, and would fool the escape hatch below into "kept".
 *
 *  THE ESCAPE HATCH. A game whose `capacitor.config.json` lists `facebook.com` in
 *  `plugins.FirebaseAuthentication.providers` keeps the SDK: that is the plugin's own switch for
 *  "this app offers Facebook sign-in", and this makes it true for SPM too. If an earlier build
 *  already stripped the manifest, that is a REFUSAL too: the plugin's whole Facebook sign-in body is
 *  behind `#if RGCFA_INCLUDE_FACEBOOK` with no `#else`, so a build without the define compiles a
 *  `signInWithFacebook` that never resolves or rejects — a hung call, not an error.
 *
 *  THE STALE PIN. Xcode's `Package.resolved` (gitignored) keeps a `facebook-ios-sdk` pin after the
 *  strip. With that pin and FRESH DerivedData, `xcodebuild` crashes resolving packages (`INTERNAL
 *  ERROR … count of array (33) differs from count of index set (32)`, exit 134 — reproduced 2 of 2
 *  in a controlled copy, and gone with the pin absent); the crashing run rewrites the file, so a
 *  retry passes. Warm DerivedData never crashes but never drops the pin either. So the strip drops
 *  the pin too. */

import fs from 'node:fs';
import path from 'node:path';

/** Where SPM reads the plugin from: `ios/App/CapApp-SPM/Package.swift` (generated by `cap sync`)
 *  points at the project's OWN `node_modules` — games are self-contained (#29), nothing is hoisted. */
export function firebaseAuthManifestPath(projectRoot: string): string {
  return path.join(projectRoot, 'node_modules', '@capacitor-firebase', 'authentication', 'Package.swift');
}

/** One self-contained array element that names Facebook — the only line shape this removes. */
const FACEBOOK_ELEMENT = /^\s*\.(?:package|product|define)\(.*(?:facebook-ios-sdk|RGCFA_INCLUDE_FACEBOOK).*\),?\s*$/;

/** Remove every Facebook element line from a plugin manifest. Pure; a manifest with none comes back
 *  byte-identical. Only whole lines go, so no neighbour is edited: Swift array literals accept the
 *  trailing comma a removed last element leaves on the one before it. */
export function stripFacebookElements(manifest: string): string {
  return manifest.split('\n').filter((line) => !FACEBOOK_ELEMENT.test(line)).join('\n');
}

/** Lines of `manifest` that still mention Facebook, in any shape — the post-condition. */
export function facebookLeftovers(manifest: string): string[] {
  return manifest.split('\n').filter((line) => /facebook/i.test(line)).map((line) => line.trim());
}

/** True when the project's Capacitor config asks for Facebook sign-in. An absent or unreadable
 *  config asks for nothing — `cap sync` would fail on an unreadable one long before it mattered. */
function providersIncludeFacebook(projectRoot: string): boolean {
  try {
    const cfg = JSON.parse(fs.readFileSync(path.join(projectRoot, 'capacitor.config.json'), 'utf8'));
    const providers: unknown = cfg?.plugins?.FirebaseAuthentication?.providers;
    return Array.isArray(providers) && providers.includes('facebook.com');
  } catch {
    return false;
  }
}

/** Xcode's resolved-package pins for the Capacitor app project — gitignored, per machine. */
export function resolvedPinsPath(projectRoot: string): string {
  return path.join(projectRoot, 'ios', 'App', 'App.xcodeproj', 'project.xcworkspace', 'xcshareddata', 'swiftpm', 'Package.resolved');
}

/** Drop a `facebook-ios-sdk` pin from `Package.resolved`, if there is one. Returns whether it wrote.
 *  An absent or unparseable file is left alone — Xcode regenerates it, and a heal must not turn a
 *  file it cannot read into a build failure. */
function dropResolvedFacebookPin(projectRoot: string): boolean {
  const file = resolvedPinsPath(projectRoot);
  let doc: { pins?: Array<{ identity?: unknown }> } | null;
  try {
    doc = JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch {
    return false;
  }
  if (!doc || !Array.isArray(doc.pins) || !doc.pins.some((p) => p?.identity === 'facebook-ios-sdk')) return false;
  doc.pins = doc.pins.filter((p) => p?.identity !== 'facebook-ios-sdk');
  fs.writeFileSync(file, `${JSON.stringify(doc, null, 2)}\n`);
  return true;
}

export type StripFirebaseAuthFacebookResult =
  | { ok: true; notes: string[] }
  /** The manifest is not in the state this project needs — `lines` is the diagnosis. Nothing written. */
  | { ok: false; lines: string[] };

/** Heal `projectRoot`'s installed plugin manifest. A project without the plugin is a no-op. */
export function stripFirebaseAuthFacebook(projectRoot: string): StripFirebaseAuthFacebookResult {
  const file = firebaseAuthManifestPath(projectRoot);
  if (!fs.existsSync(file)) return { ok: true, notes: [] };
  const before = fs.readFileSync(file, 'utf8');
  if (providersIncludeFacebook(projectRoot)) {
    // Keyed on the DEFINE, not any mention of Facebook: the define is what compiles the sign-in flow
    // in, so a manifest carrying only a comment about Facebook must still refuse here.
    // Anchored to the element-line shape, so a commented-out define does not count as present.
    if (/^\s*\.define\(\s*"RGCFA_INCLUDE_FACEBOOK"\s*\),?\s*$/m.test(before)) {
      return { ok: true, notes: ['kept the Facebook iOS SDK in @capacitor-firebase/authentication: capacitor.config.json providers lists facebook.com'] };
    }
    return {
      ok: false,
      lines: [
        `capacitor.config.json lists facebook.com in FirebaseAuthentication.providers, but ${file}`,
        'does not define RGCFA_INCLUDE_FACEBOOK — most likely an earlier build stripped it (#1062). Built like this, signInWithFacebook',
        'compiles to a call that never resolves — the plugin\'s whole Facebook flow is behind #if RGCFA_INCLUDE_FACEBOOK.',
        'Restore the plugin\'s original manifest, then build again:',
        `  (cd ${projectRoot} && rm -rf node_modules/@capacitor-firebase/authentication && npm install)`,
      ],
    };
  }
  const after = stripFacebookElements(before);
  const leftovers = facebookLeftovers(after);
  if (leftovers.length) {
    return {
      ok: false,
      lines: [
        `${file} would still reference Facebook after the #1062 strip — this build would embed the Facebook iOS SDK`,
        '(tracking-declaring privacy manifests) in an app that never offers Facebook sign-in. Nothing was changed.',
        ...leftovers.map((l) => `  • ${l}`),
        '',
        'The plugin\'s manifest no longer has the shape engine/plugins/stripFirebaseAuthFacebook.ts removes —',
        'most likely a @capacitor-firebase/authentication upgrade. Re-read its Package.swift and every',
        '#if RGCFA_INCLUDE_FACEBOOK in ios/Plugin, then update the strip. If this game DOES offer Facebook',
        'sign-in, add "facebook.com" to plugins.FirebaseAuthentication.providers in capacitor.config.json.',
      ],
    };
  }
  const notes: string[] = [];
  if (after !== before) {
    fs.writeFileSync(file, after);
    notes.push('stripped the Facebook iOS SDK from @capacitor-firebase/authentication/Package.swift (#1062)');
  }
  if (dropResolvedFacebookPin(projectRoot)) {
    notes.push('dropped the stale facebook-ios-sdk pin from ios/App/…/Package.resolved (#1062)');
  }
  return { ok: true, notes };
}
