import { describe, it, expect } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { discoverProjects } from '../../scripts/projectRoots.mjs';
import { hasInternalGames } from '../helpers/repoLayout';
import { repoFiles } from '../../scripts/repoCorpus.mjs';

/**
 * PORTABILITY GUARD — a game project must be SELF-CONTAINED (#29): it's opened
 * STANDALONE (often copied out of the repo), so no file under games/<id>/ may
 * import via a relative path that escapes its OWN folder — into the engine tree or
 * a sibling game. Such a path only resolves while the game sits inside the repo;
 * copied out, Vite fails with e.g. "failed to resolve ../../../../engine/app/...".
 * Games reach the engine via the `@modoki/engine` package specifier (the editor
 * resolves it regardless of the game's on-disk location), never a relative path.
 *
 * Concrete regression this guards: `useGameStore` was imported from
 * `../../../../engine/app/store/gameStore` (moved to `@modoki/engine/runtime`).
 */
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
// Every project under BOTH roots — games/ (internal) and demos/ (publishable).
// A demo is copied out of the repo even more often than a game is, so the
// self-containment guard matters at least as much there.
const projects = discoverProjects(repoRoot);

// KNOWN, TRACKED cross-game coupling still to resolve: chess reuses llm-test's
// on-device-LLM service (LLMService / initLLMSession). Until that's extracted to a
// shared home, allow EXACTLY these — any NEW escape still fails the guard. Keyed by
// `<repo-rel file> :: <import specifier>`.
const KNOWN_ESCAPES = new Set([
  'games/chess/runtime/ChessManager.ts :: ../../llm-test/runtime/services/initLLMSession',
  'games/chess/runtime/ChessManager.ts :: ../../llm-test/runtime/services/LLMService',
  'games/chess/runtime/ai/ChessAI.ts :: ../../../llm-test/runtime/services/LLMService',
]);

/** Every `.ts`/`.tsx` file under `dir`, git-enumerated (#771/#799) rather than a hand-rolled
 *  recursive walk. `node_modules`/`dist`/`.cache` need no exclude entry — all three are
 *  gitignored, so git enumeration drops them for free. */
function walk(dir: string): string[] {
  return repoFiles({
    under: dir,
    match: /\.(ts|tsx)$/,
    floor: 0,
  }).map(({ abs }) => abs);
}

/** Generated/vendored native build output: gitignored (so git enumeration excludes it for free —
 *  the explicit list below is belt-and-braces, matching the old walker's filter exactly rather
 *  than trusting gitignore alone), regenerated by Xcode/Gradle/`cap sync` on every build, and can
 *  be large (Pods, DerivedData) or hold third-party config with its OWN relative paths that would
 *  false-positive the native-config scan below. `walk()` above never needed this list — no
 *  project keeps `.ts`/`.tsx` source in these dirs — but `walkAll()` returns EVERY file, so
 *  without this it would walk straight into them. */
const NATIVE_GENERATED_DIRS = [
  '.gradle', '.build', 'Pods', 'DerivedData', 'xcuserdata', 'Packages', 'build',
  'capacitor-cordova-android-plugins', 'capacitor-cordova-ios-plugins',
];

/** Like `walk()`, but returns EVERY file rather than filtering to `.ts`/`.tsx`. The native-config
 *  scans below need `.pbxproj`, `Package.swift`, and `*.gradle` — none of which `walk()` can ever
 *  return by design, which is exactly how the old pbxproj check went vacuous (see below). Keep
 *  `walk()` itself untouched: the escaping-import scan above depends on it returning ONLY source
 *  files, and don't "simplify" this back into one walker — that's the regression this guards.
 *  Git-enumerated (#771/#799) rather than a hand-rolled recursive walk. */
function walkAll(dir: string): string[] {
  return repoFiles({
    under: dir,
    exclude: NATIVE_GENERATED_DIRS,
    floor: 0,
  }).map(({ abs }) => abs);
}

/** The scaffolder template is NOT a discovered project, so it sat outside this guard —
 *  yet `scaffold-project.mjs` (and the editor's File → New Project) mints EVERY new game
 *  from it, so a relative escape added here would propagate into every future project
 *  UNGUARDED and only fail once that game was opened standalone or copied out. Same blind
 *  spot #53 closed for `codeAssetRefs.test.ts`; found sweeping for siblings of it.
 *  Currently clean — this keeps it that way.
 *
 *  Only the escaping-import check walks it: the template has no `ios/` and no per-project
 *  tsconfig, so the pbxproj and node-types tests below stay on real projects. */
const TEMPLATE_ROOT = path.join(repoRoot, 'engine', 'templates', 'starter');
const importScanRoots: string[] = [
  ...projects.map((p: { dir: string }) => p.dir),
  ...(fs.existsSync(TEMPLATE_ROOT) ? [TEMPLATE_ROOT] : []),
];

/** Every relative import (static or dynamic) in a game file that resolves OUTSIDE
 *  that game's own folder, as `<repo-rel file> :: <specifier>`. */
function escapingImports(): string[] {
  const out: string[] = [];
  const importRe = /(?:from|import\()\s*['"](\.[^'"]+)['"]/g;
  for (const gameRoot of importScanRoots) {
    for (const file of walk(gameRoot)) {
      const src = fs.readFileSync(file, 'utf8');
      let m: RegExpExecArray | null;
      while ((m = importRe.exec(src)) !== null) {
        const resolved = path.resolve(path.dirname(file), m[1]);
        if (!resolved.startsWith(gameRoot + path.sep)) {
          // Forward-slash the repo-relative file so the key matches the canonical
          // KNOWN_ESCAPES entries on Windows too (path.relative yields backslashes there).
          out.push(`${path.relative(repoRoot, file).replace(/\\/g, '/')} :: ${m[1]}`);
        }
      }
    }
  }
  return out;
}

/** A relative path in a project's committed native config (`Package.swift` SPM deps, Gradle
 *  `projectDir` overrides) that resolves OUTSIDE the project's own folder — i.e. it reaches the
 *  repo's SHARED node_modules/engine tree instead of the project's OWN `node_modules/` (populated
 *  by `vendorPlugins` + the on-open `npm install`). This is the LIVE regression: `cap sync`
 *  regenerates `Package.swift`/`capacitor.settings.gradle` from a hardcoded `../`-depth, and when
 *  a plugin resolves one level deeper than Capacitor's CLI assumes it emits one `../` too many —
 *  e.g. `@capacitor/haptics` as `path: "../../../../../node_modules/@capacitor/haptics"` (five
 *  levels up from `ios/App/CapApp-SPM/` reaches the REPO root, not the project's own
 *  node_modules). Hand-reverted five times because nothing was checking it — the pbxproj check
 *  above doesn't: it only greps for the literal string "engine/packages".
 *
 *  Returns `{ escapes, inspected }`: `inspected` is the same non-vacuity guard as the pbxproj
 *  check below needs — a scan that silently touches zero files proves nothing. */
function nativeNodeModulesEscapes(): { escapes: string[]; inspected: number } {
  const escapes: string[] = [];
  let inspected = 0;
  // `.package(name: "X", path: "../../../node_modules/@capacitor/app")` — SPM local package refs.
  const swiftPathRe = /path:\s*"([^"]+)"/g;
  // `project(':x').projectDir = new File('../node_modules/@capacitor/x/android')` — Gradle module refs.
  const gradleFileRe = /new File\(\s*['"]([^'"]+)['"]\s*\)/g;
  for (const proj of projects) {
    for (const file of walkAll(proj.dir)) {
      const name = path.basename(file);
      const re = name === 'Package.swift' ? swiftPathRe : name.endsWith('.gradle') ? gradleFileRe : null;
      if (!re) continue;
      inspected++;
      const src = fs.readFileSync(file, 'utf8');
      re.lastIndex = 0;
      let m: RegExpExecArray | null;
      while ((m = re.exec(src)) !== null) {
        const ref = m[1];
        // A remote/protocol reference is not a filesystem path and cannot escape anything. An
        // ABSOLUTE one is not exempt though — it is the WORST version of this bug (a machine's own
        // checkout path, which resolves on exactly one computer), so it falls through to the
        // containment check below rather than being skipped alongside the URLs.
        if (/^[a-z][a-z0-9+.-]*:/i.test(ref)) continue;
        const resolved = path.resolve(path.dirname(file), ref);
        if (resolved !== proj.dir && !resolved.startsWith(proj.dir + path.sep)) {
          escapes.push(`${path.relative(repoRoot, file).replace(/\\/g, '/')} :: ${ref}`);
        }
      }
    }
  }
  return { escapes, inspected };
}

// Skip when NO project root exists (the OSS public repo ships engine-only — nothing to
// check portability of). docs/engine-oss-publishing.md.
describe.skipIf(!hasInternalGames())('game project portability (self-contained — no relative escapes)', () => {
  it('no game imports outside its own folder except the known tracked coupling', () => {
    const unexpected = escapingImports().filter((e) => !KNOWN_ESCAPES.has(e));
    expect(
      unexpected,
      `Games must reach the engine via '@modoki/engine', not a relative path that escapes the game folder:\n${unexpected.join('\n')}`,
    ).toEqual([]);
  });

  it('the allowlist has no stale entries (prune when a coupling is fixed)', () => {
    const escapes = new Set(escapingImports());
    const stale = [...KNOWN_ESCAPES].filter((e) => !escapes.has(e));
    expect(stale, `KNOWN_ESCAPES lists escapes that no longer exist — remove them:\n${stale.join('\n')}`).toEqual([]);
  });

  // A game must TYPECHECK standalone too, not just resolve its imports. Game code is typed
  // browser-only (`engine/tsconfig.app.json` sets `types: ["vite/client"]`), so a file that
  // imports a node builtin needs an explicit `/// <reference types="node" />` — which is
  // program-global, so ONE per project covers that project's files.
  //
  // Why a guard rather than trusting `npm run typecheck`: the root typecheck compiles app + ALL
  // projects as ONE program, so a single `/// <reference types="node" />` anywhere makes every
  // other project's node usage resolve. A per-game build (`engine/scripts/build-web.mjs` writes a
  // tsconfig scoped to the ONE game) has no such donor and fails with `Cannot find module
  // 'node:fs'`. The root typecheck therefore CANNOT catch this class — only a build can, and we
  // don't build 25 projects in CI. Regression: games/court/tests/corpus.test.ts, which passed
  // `npm run typecheck` and broke the Court iOS build.
  //
  // `tools/` is skipped: it's build-time Node code, excluded from the app tsconfig on purpose.
  it('a project using node builtins declares the node types itself (build scopes to ONE project)', () => {
    const nodeImport = /(?:from|import\()\s*['"](?:node:[a-z_/]+|fs|path|os|url|child_process|crypto)['"]/;
    const offenders: string[] = [];
    for (const proj of projects) {
      const files = walk(proj.dir).filter((f) => !f.includes(`${path.sep}tools${path.sep}`));
      const users = files.filter((f) => nodeImport.test(fs.readFileSync(f, 'utf8')));
      if (users.length === 0) continue;
      const declares = files.some((f) => /\/\/\/\s*<reference\s+types="node"\s*\/>/.test(fs.readFileSync(f, 'utf8')));
      if (!declares) {
        offenders.push(
          `${proj.root}/${proj.name}: ${users.map((f) => path.relative(repoRoot, f).replace(/\\/g, '/')).join(', ')}`,
        );
      }
    }
    expect(
      offenders,
      'Add `/// <reference types="node" />` to one of these files (see games/sling/tests/sling-assets.test.ts);\n' +
      `otherwise the per-game build fails on "Cannot find module 'node:fs'":\n${offenders.join('\n')}`,
    ).toEqual([]);
  });

  // Native projects must be self-contained too: the iOS pbxproj once referenced
  // GameDebugPlugin.swift by a repo-relative path (../../../../engine/packages/…),
  // which broke a standalone build ("GameDebug plugin is not implemented on ios").
  // Native code a game compiles must come from the game's OWN node_modules, never
  // the repo. (Android already does this via capacitor.settings.gradle.)
  //
  // ⚠️ This check was DEAD for months and nobody noticed: it used to do
  // `walk(iosDir).filter(f => f.endsWith('.pbxproj'))`, but `walk()` only ever returns
  // `.ts`/`.tsx` files (see its filter above) — `.pbxproj` never survives it, so the filtered
  // list was ALWAYS `[]` and `expect([]).toEqual([])` passed vacuously no matter what the pbxproj
  // said. `.xcodeproj` is a DIRECTORY on macOS (a bundle) containing `project.pbxproj`, and
  // `walkAll()` (unlike `walk()`) walks into it. The `pbxprojFound` assertion below exists so a
  // future "simplify the walker" can't silently reintroduce the same vacuity.
  it('no committed iOS pbxproj references the repo engine via a path (use node_modules)', () => {
    const offenders: string[] = [];
    let projectsWithIos = 0;
    let pbxprojFound = 0;
    for (const proj of projects) {
      const iosDir = path.join(proj.dir, 'ios');
      if (!fs.existsSync(iosDir)) continue;
      projectsWithIos++;
      for (const file of walkAll(iosDir).filter((f) => f.endsWith('.pbxproj'))) {
        pbxprojFound++;
        const src = fs.readFileSync(file, 'utf8');
        // A `path = "…"` entry that reaches the repo's engine/packages tree.
        const m = src.match(/path = "[^"]*engine\/packages\/[^"]*"/g);
        if (m) offenders.push(`${path.relative(repoRoot, file).replace(/\\/g, '/')}: ${m.join(', ')}`);
      }
    }
    if (projectsWithIos > 0) {
      expect(
        pbxprojFound,
        'no .pbxproj was found under any ios/ directory even though ios/ exists — the walker is ' +
          'broken again (see the comment above this test).',
      ).toBeGreaterThan(0);
    }
    expect(
      offenders,
      `iOS pbxproj must reference plugin sources via the game's node_modules, not the repo:\n${offenders.join('\n')}`,
    ).toEqual([]);
  });

  // The live regression the check above CANNOT catch: it only greps for the literal string
  // "engine/packages", so it says nothing about a plugin path that escapes the project into the
  // repo's SHARED node_modules instead — which is exactly what `cap sync` re-emits (see
  // nativeNodeModulesEscapes() for the concrete `../../../../../node_modules/@capacitor/haptics`
  // shape). A project's native config must resolve every relative plugin path to ITS OWN
  // node_modules, never past its own folder.
  it("no committed native config (Package.swift / gradle) resolves a plugin path outside its own project's node_modules", () => {
    const { escapes, inspected } = nativeNodeModulesEscapes();
    // Same self-guard as the pbxproj check above: every discovered project ships an
    // `ios/App/CapApp-SPM/Package.swift` and an `android/capacitor.settings.gradle`, so a scan
    // that inspects zero files is broken, not clean.
    expect(
      inspected,
      'no Package.swift / .gradle file was inspected across any project — the native scan is dead.',
    ).toBeGreaterThan(0);
    expect(
      escapes,
      "Native config must resolve plugin paths inside the project's OWN node_modules, not escape " +
        `into the repo:\n${escapes.join('\n')}`,
    ).toEqual([]);
  });
});
