/** Pure path/tree helpers for the Assets panel. Extracted from Assets.tsx so the
 *  logic (compound-extension splitting, collision-free copy/paste names, folder
 *  rename remapping, folder-tree building) can be unit-tested without rendering
 *  the React component. */

import type { SpriteAssetRef } from '../../runtime/loaders/spriteSheet';

export interface AssetEntry {
  guid?: string;
  path: string;
  name: string;
  type: string;
  /** Sliced-sprite block (`type === 'sprite'` only) — parent texture + rect/pivot.
   *  Lets the Assets panel nest sprites under their texture (Unity-style sub-assets). */
  sprite?: SpriteAssetRef;
}

export interface FolderNode {
  name: string;
  path: string;         // folder path like "/models/tropical-island"
  children: FolderNode[];
  files: AssetEntry[];
}

/** Split an asset path into its folder, base filename, and extension. Splits
 *  on the FIRST dot so compound extensions (.prefab.json, .mat.json, .meta.json)
 *  stay intact — the base is what the user edits when renaming/duplicating.
 *  A LEADING dot (dotfile like `.gitkeep`) is part of the base, not an empty-base
 *  extension — start scanning for the extension dot at index 1 in that case so a
 *  dotfile rename/duplicate keeps its name instead of producing `${dir}/ copy.gitkeep`. */
export function splitAssetPath(p: string): { dir: string; base: string; ext: string } {
  const slash = p.lastIndexOf('/');
  const dir = slash >= 0 ? p.substring(0, slash) : '';
  const filename = slash >= 0 ? p.substring(slash + 1) : p;
  const dot = filename.indexOf('.', filename.startsWith('.') ? 1 : 0);
  const base = dot >= 0 ? filename.substring(0, dot) : filename;
  const ext = dot >= 0 ? filename.substring(dot) : '';
  return { dir, base, ext };
}

/** Plan which freshly-discovered assets to auto-import with default config
 *  (Unity-style import-on-add). PURE so the policy is unit-tested without IO.
 *
 *  `added` = the entries that just appeared on disk (the diff vs the previous
 *  scan). `allPaths` = the full current path set, used to spot existing import
 *  OUTPUTS so a model isn't re-imported.
 *
 *   - MODEL → import (creates a prefab; FBX/OBJ/DAE bake to GLB first), UNLESS a
 *     sibling `<name>.prefab.json` already exists — that's the import output, so
 *     the model has already been imported.
 *   - TEXTURE → import (convert with default config). No sibling marker, but only
 *     genuinely-new entries are ever passed, so each converts exactly once.
 *
 *  Everything else (prefab / mesh / material / scene / sidecars / …) is an import
 *  OUTPUT, not a source — ignored, so import results never re-trigger imports. The
 *  sibling check uses last-extension stripping (NOT splitAssetPath's first-dot
 *  split) to match importModelWithMeta's prefab path for multi-dot model names. */
export function planAutoImports(
  added: ReadonlyArray<AssetEntry>,
  allPaths: ReadonlySet<string>,
): { models: AssetEntry[]; textures: AssetEntry[] } {
  const models: AssetEntry[] = [];
  const textures: AssetEntry[] = [];
  for (const a of added) {
    if (a.type === 'model') {
      // A `.colmesh.glb` is collision SOURCE geometry (generated by the Model
      // inspector's "Generate Collision Mesh"), not a render model — importing it
      // would wrongly mint a prefab/material + a stray scene mesh. Its own lean
      // `.mesh.json` is hand-authored, so treat it as an import output, not a source.
      if (a.path.endsWith('.colmesh.glb')) continue;
      const prefabSibling = a.path.replace(/\.[^./]+$/, '.prefab.json');
      if (!allPaths.has(prefabSibling)) models.push(a);
    } else if (a.type === 'texture') {
      textures.push(a);
    }
  }
  return { models, textures };
}

/** Build a non-colliding "X copy" path for a duplicate. */
export function duplicatePathFor(srcPath: string, taken: Set<string>): string {
  const { dir, base, ext } = splitAssetPath(srcPath);
  const make = (suffix: string) => `${dir}/${base}${suffix}${ext}`;
  let candidate = make(' copy');
  let n = 2;
  while (taken.has(candidate)) { candidate = make(` copy ${n}`); n++; }
  return candidate;
}

/** Destination path when pasting `srcPath` into `folder`, avoiding collisions
 *  (appends " copy" / " copy N", preserving compound extensions). */
export function pastePathIn(folder: string, srcPath: string, taken: Set<string>): string {
  const { base, ext } = splitAssetPath(srcPath);
  const norm = folder === '/' ? '' : folder;
  let candidate = `${norm}/${base}${ext}`;
  if (!taken.has(candidate)) return candidate;
  candidate = `${norm}/${base} copy${ext}`;
  let n = 2;
  while (taken.has(candidate)) { candidate = `${norm}/${base} copy ${n}${ext}`; n++; }
  return candidate;
}

/** Rewrite a path-set after a folder rename: any entry equal to or under
 *  `oldP` is reparented to `newP`. Used to keep the expanded/pending sets
 *  consistent when a folder (and its whole subtree) is renamed. */
export function remapPrefix(set: Set<string>, oldP: string, newP: string): Set<string> {
  const next = new Set<string>();
  for (const v of set) {
    if (v === oldP) next.add(newP);
    else if (v.startsWith(oldP + '/')) next.add(newP + v.slice(oldP.length));
    else next.add(v);
  }
  return next;
}

/** Collapse a single-folder wrapper chain so redundant manifest roots (e.g. the
 *  virtual `/` named "assets" wrapping the `/assets` URL-prefix folder, also named
 *  "assets") don't render as "assets ▸ assets". Descends while a node has no files
 *  and exactly one child folder, landing on the first node that actually branches
 *  (where the category folders live). Shared by the project + Engine sections. */
export function effectiveAssetsRoot(root: FolderNode): FolderNode {
  let node = root;
  while (node.files.length === 0 && node.children.length === 1) node = node.children[0];
  return node;
}

/** All folder paths in a subtree (the node itself + every descendant folder) —
 *  used for Option/Alt-click "expand/collapse all". */
export function collectFolderPaths(node: FolderNode, out: string[] = []): string[] {
  out.push(node.path);
  for (const c of node.children) collectFolderPaths(c, out);
  return out;
}

/** Build a hierarchical folder tree from a flat asset list. `extraFolders`
 *  seeds folders that hold no assets (freshly-created empty folders) so they
 *  still appear — the backend scanner only reports files. */
export function buildFolderTree(assets: AssetEntry[], extraFolders: string[] = []): FolderNode {
  const root: FolderNode = { name: 'assets', path: '/', children: [], files: [] };
  const folderMap = new Map<string, FolderNode>();
  folderMap.set('/', root);

  const getOrCreate = (folderPath: string): FolderNode => {
    if (folderMap.has(folderPath)) return folderMap.get(folderPath)!;
    const parts = folderPath.split('/').filter(Boolean);
    const name = parts[parts.length - 1];
    const parentPath = '/' + parts.slice(0, -1).join('/');
    const parent = getOrCreate(parentPath.length > 1 ? parentPath : '/');
    const node: FolderNode = { name, path: folderPath, children: [], files: [] };
    parent.children.push(node);
    folderMap.set(folderPath, node);
    return node;
  };

  for (const a of assets) {
    const lastSlash = a.path.lastIndexOf('/');
    const folderPath = lastSlash > 0 ? a.path.substring(0, lastSlash) : '/';
    getOrCreate(folderPath).files.push(a);
  }
  // Seed folders that hold no assets (freshly-created empty folders).
  for (const f of extraFolders) { if (f && f !== '/') getOrCreate(f); }

  // Sort children and files alphabetically.
  const sortNode = (node: FolderNode) => {
    node.children.sort((a, b) => a.name.localeCompare(b.name));
    node.files.sort((a, b) => a.name.localeCompare(b.name));
    node.children.forEach(sortNode);
  };
  sortNode(root);
  return root;
}
