/** Stable GUIDs for assets that SHIP WITH THE ENGINE (served from /modoki/assets,
 *  resolvable in every project). Single source of truth so the runtime that
 *  references a built-in and the sidecar `.meta.json` on disk can never drift —
 *  guarded by tests/assets/whiteHdr.test.ts. */

/** The engine's procedurally-generated `white.hdr` — the default environment for
 *  freshly-created scenes (see `newScene()`). Generated by
 *  `engine/scripts/gen-white-hdr.mjs`; must equal the id in its `.meta.json`. */
export const WHITE_HDR_GUID = 'beef0000-0000-4000-8000-000000000001';

/** The engine's DEFAULT MSDF text font — Arimo (Apache-2.0, Arial-metric), baked
 *  mtsdf/ascii by its committed `.meta.json`. Fonts are normally referenced by CSS
 *  family name and stay guid-less (see the healing skip in vite-asset-scanner), but
 *  a `Text2D` ref must be a GUID — so without ONE blessed built-in, every game had
 *  to copy a font into its own assets to get MSDF text at all. Games reach this as
 *  `DEFAULT_FONT_GUID` from `@modoki/engine/runtime`; the tree-shaker keeps it by
 *  family like any other font, so a game that never names it ships nothing.
 *  Must equal the id in `fonts/Arimo/Arimo-VariableFont_wght.ttf.meta.json`. */
export const DEFAULT_FONT_GUID = 'beef0000-0000-4000-8000-000000000002';
