/** Stable GUIDs for assets that SHIP WITH THE ENGINE (served from /modoki/assets,
 *  resolvable in every project). Single source of truth so the runtime that
 *  references a built-in and the sidecar `.meta.json` on disk can never drift —
 *  guarded by tests/assets/whiteHdr.test.ts. */

/** The engine's procedurally-generated `white.hdr` — the default environment for
 *  freshly-created scenes (see `newScene()`). Generated by
 *  `engine/scripts/gen-white-hdr.mjs`; must equal the id in its `.meta.json`. */
export const WHITE_HDR_GUID = 'beef0000-0000-4000-8000-000000000001';
