// Cross-tool verification for OtaZip: reads a REAL zip file produced by the Node writer
// (engine/scripts/ota/zip.mjs) that `unzip`/`zipinfo` (system CLI, an independent
// implementation of the ZIP format) already confirmed is valid — proving OtaZip parses
// authentic ZIP structure, not just its own writer's output in isolation.
//
// Regenerate the fixture with (see docs/ota-updates.md for the full command); `npm run
// test:native` already builds and passes this fixture via MODOKI_OTA_ZIP_FIXTURE, so this is only
// needed to reproduce /tmp/ota-test.zip by hand:
//   node --input-type=module -e "
//     import {buildZip} from './engine/scripts/ota/zip.mjs';
//     import {writeFileSync} from 'node:fs';
//     const entries = [
//       {path: 'index.html', data: Buffer.from('<html>hi</html>', 'utf8')},
//       {path: 'assets/app.js', data: Buffer.from('console.log(1)'.repeat(50), 'utf8')},
//       {path: 'assets/tiny.txt', data: Buffer.from('x', 'utf8')},
//       {path: 'empty.txt', data: Buffer.alloc(0)},
//     ];
//     writeFileSync('/tmp/ota-test.zip', buildZip(entries));
//   "

import XCTest
@testable import ModokiOtaCore

final class OtaZipTests: XCTestCase {
  func testRoundTripAgainstNodeProducedZip() throws {
    // Build the exact same fixture inline (rather than depending on a checked-in binary
    // .zip in the repo) so the test is self-contained and reproducible without Node
    // present at test time — the CROSS-tool check (this same content, unzip'd by both
    // Node's own writer's neighbor `unzip` CLI, and by hand below) already happened
    // manually and is recorded in docs/ota-updates.md; this test locks the Swift reader's
    // behavior against a byte-for-byte reproduction of that verified fixture.
    // A skipped XCTest still exits 0, so this test must not degrade into a silent no-op
    // when `test:native`'s runner actually expects it to run. `MODOKI_OTA_ZIP_FIXTURE`
    // SET (by the runner) but pointing at a file that doesn't exist means the fixture was
    // supposed to be there and wasn't — that's a real failure (a regression for #565: a
    // deleted/misconfigured fixture row must go red, not quietly restore #565 with nothing
    // red to show for it). Only a bare `swift test` run directly, with the env var absent
    // entirely, gets the graceful XCTSkip — that's a human running this file in isolation
    // without the fixture set up at all.
    let envFixturePath = ProcessInfo.processInfo.environment["MODOKI_OTA_ZIP_FIXTURE"]
    let zipPath = envFixturePath ?? "/tmp/ota-test.zip"
    if !FileManager.default.fileExists(atPath: zipPath) {
      if envFixturePath != nil {
        XCTFail("MODOKI_OTA_ZIP_FIXTURE=\(zipPath) was set but the file does not exist — the runner (npm run test:native) was supposed to generate it first.")
        return
      }
      throw XCTSkip("Fixture not present at \(zipPath) — normally generated by `npm run test:native`; regenerate by hand via the node command in this file's header comment before running this test directly.")
    }
    let archive = try Data(contentsOf: URL(fileURLWithPath: zipPath))
    let entries = try OtaZip.unzip(archive)

    let byPath = Dictionary(uniqueKeysWithValues: entries.map { ($0.path, $0.data) })
    XCTAssertEqual(Set(byPath.keys), Set(["index.html", "assets/app.js", "assets/tiny.txt", "empty.txt"]))
    XCTAssertEqual(byPath["index.html"], "<html>hi</html>".data(using: .utf8))
    XCTAssertEqual(byPath["assets/app.js"], "console.log(1)".repeated(50).data(using: .utf8))
    XCTAssertEqual(byPath["assets/tiny.txt"], "x".data(using: .utf8))
    // A zero-byte file is a real edge case (empty JSON, placeholder asset) — the decoder
    // must not choke on compressedSize==0/uncompressedSize==0.
    XCTAssertEqual(byPath["empty.txt"], Data())
  }

  func testRejectsNonZipData() {
    XCTAssertThrowsError(try OtaZip.unzip(Data("not a zip file".utf8)))
  }

  // MARK: - Zip-slip guard (F6)

  /// Hand-builds a minimal STORED-only ZIP (no compression, so no dependency on the
  /// deflate path being correct) with an attacker-chosen entry NAME — the one field
  /// `OtaZip.unzip` cannot get from a well-behaved writer, since `ota-publish.mjs`'s own
  /// `zip.mjs` never emits a traversal path. CRC/mod-time are left as 0 — `OtaZip` never
  /// verifies them, and the zip-slip guard fires before the payload is even read.
  private func buildStoredZip(_ entries: [(path: String, data: Data)]) -> Data {
    func u16le(_ n: Int) -> [UInt8] { let v = UInt16(n & 0xffff); return [UInt8(v & 0xff), UInt8((v >> 8) & 0xff)] }
    func u32le(_ n: Int) -> [UInt8] {
      let v = UInt32(truncatingIfNeeded: n)
      return [UInt8(v & 0xff), UInt8((v >> 8) & 0xff), UInt8((v >> 16) & 0xff), UInt8((v >> 24) & 0xff)]
    }
    var localBytes: [UInt8] = []
    var centralBytes: [UInt8] = []
    var offset = 0
    for (path, data) in entries {
      let nameBytes = [UInt8](path.utf8)
      let payload = [UInt8](data)
      var localHeader: [UInt8] = []
      localHeader += u32le(0x04034b50)
      localHeader += u16le(20) // version needed
      localHeader += u16le(0) // flags
      localHeader += u16le(0) // method: stored
      localHeader += u16le(0) + u16le(0) // mod time/date
      localHeader += u32le(0) // crc — unchecked by the reader
      localHeader += u32le(payload.count) // compressed size
      localHeader += u32le(payload.count) // uncompressed size
      localHeader += u16le(nameBytes.count)
      localHeader += u16le(0) // extra field length
      localHeader += nameBytes
      localBytes += localHeader
      localBytes += payload

      var centralHeader: [UInt8] = []
      centralHeader += u32le(0x02014b50)
      centralHeader += u16le(20) // version made by
      centralHeader += u16le(20) // version needed
      centralHeader += u16le(0) // flags
      centralHeader += u16le(0) // method
      centralHeader += u16le(0) + u16le(0) // mod time/date
      centralHeader += u32le(0) // crc
      centralHeader += u32le(payload.count)
      centralHeader += u32le(payload.count)
      centralHeader += u16le(nameBytes.count)
      centralHeader += u16le(0) + u16le(0) // extra/comment length
      centralHeader += u16le(0) // disk number start
      centralHeader += u16le(0) // internal attrs
      centralHeader += u32le(0) // external attrs
      centralHeader += u32le(offset) // local header offset
      centralHeader += nameBytes
      centralBytes += centralHeader

      offset += localHeader.count + payload.count
    }
    var eocd: [UInt8] = []
    eocd += u32le(0x06054b50)
    eocd += u16le(0) + u16le(0) // disk numbers
    eocd += u16le(entries.count)
    eocd += u16le(entries.count)
    eocd += u32le(centralBytes.count)
    eocd += u32le(offset)
    eocd += u16le(0) // comment length
    return Data(localBytes + centralBytes + eocd)
  }

  private func assertUnsafeEntryPath(_ archive: Data, file: StaticString = #filePath, line: UInt = #line) {
    XCTAssertThrowsError(try OtaZip.unzip(archive), file: file, line: line) { error in
      guard case OtaZipError.unsafeEntryPath = error else {
        XCTFail("expected .unsafeEntryPath, got \(error)", file: file, line: line)
        return
      }
    }
  }

  func testRejectsRelativeTraversalEntryPath() {
    assertUnsafeEntryPath(buildStoredZip([(path: "../evil.txt", data: Data("pwned".utf8))]))
  }

  func testRejectsNestedTraversalEntryPath() {
    assertUnsafeEntryPath(buildStoredZip([(path: "assets/../../evil.txt", data: Data("pwned".utf8))]))
  }

  func testRejectsAbsoluteEntryPath() {
    assertUnsafeEntryPath(buildStoredZip([(path: "/etc/passwd", data: Data("pwned".utf8))]))
  }

  func testAcceptsOrdinaryRelativeEntryPath() throws {
    let archive = buildStoredZip([(path: "assets/ok.txt", data: Data("fine".utf8))])
    let entries = try OtaZip.unzip(archive)
    XCTAssertEqual(entries.first?.path, "assets/ok.txt")
    XCTAssertEqual(entries.first?.data, Data("fine".utf8))
  }
}

private extension String {
  func repeated(_ n: Int) -> String { String(repeating: self, count: n) }
}
